"""Study tools: cheat sheet, explain a page, bilingual glossary, concept map."""
import pandas as pd
import streamlit as st

from core import store, study
from core.export import glossary_csv, glossary_markdown, markdown_to_pdf
from core.ingest import fmt_ref
from core.llm import LLMError
from views.ui import demo_guard, markdown, page_header, progress_bar

ss = st.session_state
page_header("📋", "Study tools",
            "Cheat sheets, page explanations in Arabic or English, a bilingual glossary and concept maps.")
if not ss.selected_docs:
    st.info("Select a document in the sidebar.")
    st.stop()

doc = st.selectbox("Document", ss.selected_docs, format_func=ss.doc_labels.get) \
    if len(ss.selected_docs) > 1 else ss.selected_docs[0]
fname, unit, n_units = ss.doc_names[doc], ss.doc_units.get(doc, "page"), ss.doc_pages.get(doc, 1)
stem = fname.rsplit(".", 1)[0]

t_sheet, t_explain, t_gloss, t_map = st.tabs(["📋 Cheat sheet", "🌍 Explain a page", "📖 Glossary", "🧠 Concept map"])


def run(fn, *args, **kwargs):
    """Call a study tool with a progress bar; show LLM errors instead of crashing."""
    bar, cb = progress_bar()
    try:
        return fn(*args, progress=cb, **kwargs)
    except LLMError as e:
        st.error(str(e))
    finally:
        bar.empty()


# ---------------------------------------------------------------- cheat sheet
with t_sheet:
    st.caption("A one-page summary of the lecture: key ideas, definitions, numbers and likely exam points, "
               "each with its source.")
    c1, c2 = st.columns([2, 3])
    lang = study.LANGUAGES[c1.radio("Language", list(study.LANGUAGES), horizontal=True, key="sheet_lang")]
    key = store.note_key("cheatsheet", [doc], lang=lang, pages=None)
    sheet = store.get_note(key)
    if c2.button("Regenerate" if sheet else "Generate cheat sheet", type="secondary" if sheet else "primary",
                 key="sheet_go"):
        demo_guard(3)
        sheet = run(study.cheat_sheet, doc, fname, lang, refresh=True)
    if sheet:
        with st.container(border=True):
            markdown(sheet)
        d1, d2, _ = st.columns([1, 1, 3])
        d1.download_button("Markdown", sheet, f"{stem}-cheatsheet.md", "text/markdown", use_container_width=True)
        d2.download_button("PDF", markdown_to_pdf(sheet, f"Cheat sheet: {fname}"), f"{stem}-cheatsheet.pdf",
                           "application/pdf", use_container_width=True)

# ---------------------------------------------------------------- explain a page
with t_explain:
    label = {"page": "Page", "slide": "Slide", "part": "Part"}[unit]
    c1, c2, c3 = st.columns([1, 2, 2])
    page = c1.number_input(label, 1, max(1, n_units), 1, key="explain_page")
    lang = study.LANGUAGES[c2.radio("Explain in", list(study.LANGUAGES), index=1, horizontal=True,
                                    key="explain_lang")]
    cached = store.get_note(store.note_key("explain", [doc], page=int(page), lang=lang))
    go = c3.button("Explain again" if cached else "Explain", type="secondary" if cached else "primary",
                   key="explain_go")
    ref, text = study.page_text(doc, int(page))
    left, right = st.columns(2)
    with left:
        st.markdown(f"**Original · {ref}**")
        st.container(height=420, border=True).text(text or f"No text on this {unit}.")
    with right:
        st.markdown("**Explanation**")
        box = st.container(height=420, border=True)
        if cached and not go:
            markdown(cached, box)
        elif go and text:
            try:
                demo_guard(1)
                key, out = study.explain_page(doc, fname, int(page), lang, refresh=True)
                with box:
                    answer = st.write_stream(out) if not isinstance(out, str) else out
                if answer:
                    store.save_note(key, "explain", [doc], answer)
                    st.rerun()  # re-render from the cache, right-to-left for Arabic
            except LLMError as e:
                st.error(str(e))
        else:
            box.caption(f"Choose a {unit} and press **Explain**.")

# ---------------------------------------------------------------- glossary
with t_gloss:
    st.caption("Key technical terms with their Arabic translation and a definition in both languages. "
               "Translations are machine-generated by a small local model: double-check unfamiliar ones.")
    c1, c2 = st.columns([2, 3])
    max_terms = c1.slider("Maximum terms", 10, 40, 25, step=5, key="gloss_n")
    cached = store.get_note(store.note_key("glossary", [doc], n=max_terms))
    terms = study.glossary(doc, max_terms) if cached else None
    if c2.button("Rebuild glossary" if terms else "Build glossary", type="secondary" if terms else "primary",
                 key="gloss_go"):
        demo_guard(4)
        terms = run(study.glossary, doc, max_terms, refresh=True)
    if terms:
        q = st.text_input("Search", placeholder="Filter terms (English or Arabic)", key="gloss_q").strip().casefold()
        shown = [t for t in terms if not q or q in t.term.casefold() or q in t.arabic or q in t.definition_en.casefold()]
        st.dataframe(pd.DataFrame([{"Term": t.term, "Arabic": t.arabic, "Definition": t.definition_en,
                                    "التعريف": t.definition_ar, "Source": t.ref} for t in shown]),
                     hide_index=True, use_container_width=True)
        st.caption(f"{len(shown)} of {len(terms)} terms")
        d1, d2, _ = st.columns([1, 1, 3])
        d1.download_button("CSV (Excel)", glossary_csv(terms), f"{stem}-glossary.csv", "text/csv",
                           use_container_width=True)
        d2.download_button("Markdown", glossary_markdown(terms, f"Glossary: {fname}"), f"{stem}-glossary.md",
                           "text/markdown", use_container_width=True)
    elif terms == []:
        st.warning("No terms could be extracted from this document.")

# ---------------------------------------------------------------- concept map
with t_map:
    st.caption("The main concepts of the lecture and how they relate. Built from the English cheat sheet "
               "(generated first if needed).")
    c1, c2 = st.columns([2, 3])
    n_concepts = c1.slider("Concepts", 6, 20, 12, key="map_n")
    cached = store.get_note(store.note_key("conceptmap", [doc], n=n_concepts))
    cmap = study.concept_map(doc, fname, n_concepts) if cached else None
    if c2.button("Redraw" if cmap else "Draw concept map", type="secondary" if cmap else "primary", key="map_go"):
        demo_guard(2 if store.latest_note("cheatsheet", doc) else 5)
        cmap = run(study.concept_map, doc, fname, n_concepts, refresh=True)
        if cmap is None:
            st.warning("The model did not return a usable concept map. Try again or change the number of concepts.")
    if cmap:
        st.graphviz_chart(study.to_dot(cmap, unit), use_container_width=True)
        st.caption(f"{len(cmap.nodes)} concepts · {len(cmap.edges)} links · numbers are the source "
                   f"{unit}s ({fmt_ref(unit, 1).replace('1', 'N')})")
        st.download_button("Mermaid (for Notion, Obsidian, GitHub)", study.to_mermaid(cmap), f"{stem}-concept-map.mmd",
                           "text/plain")
